import type { QuizQuestion } from '@/content/types'

/**
 * Knowledge checks that test understanding, not memorization (Section 4).
 * Drawn from the same knowledge base as Learn/Aha/Daily.
 */
export const quizQuestions: QuizQuestion[] = [
  {
    slug: 'what-command-for-diff',
    prompt: 'You edited index.html and want Git to tell you exactly what changed. Which command should you use?',
    choices: ['git diff', 'git status', 'git log', 'git show'],
    correctIndex: 0,
    explanation: 'git status tells you that index.html changed; git diff shows the actual line-by-line changes inside it.',
    relatedConcepts: ['working-directory'],
    difficulty: 'beginner',
  },
  {
    slug: 'git-vs-github-quiz',
    prompt: 'Which of these can you do without ever creating a GitHub account?',
    scenario: "You're on a plane with no internet connection.",
    choices: [
      'Nothing — Git needs GitHub to work at all',
      'git init, git add, git commit, and git log',
      'Only git status, nothing that changes history',
      'Only viewing history, not creating commits',
    ],
    correctIndex: 1,
    explanation: 'Git runs entirely on your machine. Initializing a repo, staging, committing, and viewing history all work with zero internet connection and no GitHub account.',
    relatedConcepts: ['git-vs-github'],
    difficulty: 'beginner',
  },
  {
    slug: 'does-add-commit',
    prompt: 'After running git add index.html, is that change permanently recorded in your project history?',
    choices: ['Yes, immediately', 'No — it\'s only staged until git commit runs', 'Only if you also run git push', 'Only if you close and reopen the file'],
    correctIndex: 1,
    explanation: 'git add moves the change into the staging area — a waiting room. Nothing is recorded in history until git commit runs.',
    relatedConcepts: ['staging-area'],
    difficulty: 'beginner',
  },
  {
    slug: 'staging-area-purpose',
    prompt: "You've changed three files but only want to commit one of them right now. What lets you do that?",
    choices: ['git commit --only', 'The staging area — git add just the one file', 'You have to commit all three together', 'git branch a temporary branch first'],
    correctIndex: 1,
    explanation: 'The staging area exists exactly for this — git add lets you choose which changes go into the next commit, leaving the rest for later.',
    relatedConcepts: ['staging-area'],
    difficulty: 'beginner',
  },
  {
    slug: 'clone-vs-pull-quiz',
    prompt: 'A teammate sends you a link to their GitHub repository, and you\'ve never downloaded it before. What do you run?',
    choices: ['git pull', 'git fetch', 'git clone', 'git init'],
    correctIndex: 2,
    explanation: "git clone is for getting a project you don't have yet. git pull and git fetch assume you already have a local copy.",
    relatedConcepts: ['remote'],
    difficulty: 'beginner',
  },
  {
    slug: 'fetch-does-not-change-files',
    prompt: 'After running git fetch, do the files in your working directory change?',
    choices: [
      'Yes, they update to match the remote immediately',
      'No — fetch only updates what Git knows about the remote',
      'Only if there were no conflicts',
      'Yes, but only staged files update',
    ],
    correctIndex: 1,
    explanation: "git fetch downloads new commits and updates Git's record of the remote branches, but doesn't touch your working directory. git merge or git pull is what actually brings the changes into your files.",
    relatedConcepts: ['remote'],
    difficulty: 'intermediate',
  },
  {
    slug: 'branch-creation-cost',
    prompt: 'Why is creating a new Git branch on a huge project almost instant?',
    choices: [
      'Git only tracks small projects efficiently',
      'A branch is just a pointer to a commit, not a copy of the project',
      'Branches are created in the background and finish later',
      'Git compresses the whole project first',
    ],
    correctIndex: 1,
    explanation: 'A branch is a lightweight, movable pointer to a commit — creating one is just writing a new pointer, not duplicating any files.',
    relatedConcepts: ['branch'],
    difficulty: 'beginner',
  },
  {
    slug: 'merge-conflict-meaning',
    prompt: "Git tells you there's a merge conflict. What does that actually mean?",
    choices: [
      'Your project is broken and some work is gone',
      'Two branches changed the same lines and Git needs you to choose how to combine them',
      'You need to delete one of the branches',
      'Git has crashed and needs to be reinstalled',
    ],
    correctIndex: 1,
    explanation: "A merge conflict just means Git found overlapping changes it can't automatically combine. Nothing is lost — you resolve it by editing the file and committing.",
    relatedConcepts: ['merge-conflict'],
    difficulty: 'beginner',
  },
  {
    slug: 'undo-shared-commit',
    prompt: 'You need to undo a commit that a teammate has already pulled onto their machine. Which command keeps things clean for them?',
    scenario: 'Both of you are actively working off the same branch.',
    choices: ['git reset --hard', 'git revert', 'git push --force', 'git clean'],
    correctIndex: 1,
    explanation: "git revert adds a new commit undoing the old one, without rewriting history — safe for anyone who already pulled. git reset --hard and git push --force rewrite or discard history, which can cause real problems for collaborators.",
    relatedConcepts: ['commit'],
    difficulty: 'intermediate',
  },
  {
    slug: 'restore-staged-vs-plain',
    prompt: 'You staged a file by mistake with git add, but you want to keep the edits — just unstage them. What do you run?',
    choices: ['git restore <file>', 'git restore --staged <file>', 'git reset --hard', 'git clean -f'],
    correctIndex: 1,
    explanation: 'git restore --staged only removes the file from staging, keeping your edits. Plain git restore (no --staged) would discard the actual edits instead.',
    relatedConcepts: ['staging-area'],
    difficulty: 'intermediate',
  },
  {
    slug: 'stash-purpose',
    prompt: "You're mid-way through a change, but need to urgently switch branches with a clean working directory. What's the safest move?",
    choices: ['git reset --hard', 'git stash', 'git clean -f', 'Delete the changed files manually'],
    correctIndex: 1,
    explanation: 'git stash sets your uncommitted changes aside without committing or discarding them, leaving a clean working directory — you can bring them back later with git stash pop.',
    relatedConcepts: ['working-directory'],
    difficulty: 'intermediate',
  },
  {
    slug: 'detached-head-quiz',
    prompt: 'You checked out an old commit directly (not a branch) to look at it, and Git says you\'re in "detached HEAD." Is anything wrong?',
    choices: [
      'Yes, the repository is now broken',
      'No — you\'re just viewing history outside of any branch; just be careful about making new commits here',
      'Yes, you need to reinstall Git',
      'No, but all your branches have just been deleted',
    ],
    correctIndex: 1,
    explanation: "Detached HEAD just means HEAD points directly at a commit instead of a branch. It's fine for looking around — just create a branch first if you make commits you want to keep.",
    relatedConcepts: ['detached-head', 'head'],
    difficulty: 'intermediate',
  },
  {
    slug: 'reflog-recovery',
    prompt: "You ran git reset --hard and now believe you've lost a commit. Is it definitely gone?",
    choices: [
      'Yes, --hard means permanent and unrecoverable',
      'Not necessarily — git reflog often still has a record of it',
      'Only GitHub support can recover it',
      'Yes, unless you had already pushed it',
    ],
    correctIndex: 1,
    explanation: "git reset --hard discards working-directory changes permanently, but the commit itself usually still exists and shows up in git reflog for a while — from there it can be recovered.",
    relatedConcepts: ['commit', 'head'],
    difficulty: 'advanced',
  },
  {
    slug: 'push-vs-commit',
    prompt: "You've been committing locally all day but haven't run git push yet. Does your teammate see your work on GitHub?",
    choices: ['Yes, commits appear on GitHub automatically', 'No — commits stay local until you push them', 'Only if you also run git pull', 'Only if you\'re on the main branch'],
    correctIndex: 1,
    explanation: 'Committing only records history in your local repository. git push is the step that sends those commits to a remote like GitHub.',
    relatedConcepts: ['remote', 'commit'],
    difficulty: 'beginner',
  },
]
