import type { GitCommand } from '@/content/types'

/**
 * GitBit Quick's command reference (Section 28/29/31). Prioritizes
 * everyday Git + Git/GitHub + branching + the most common undo
 * commands, matching Phase 4's scope.
 */
export const commands: GitCommand[] = [
  {
    slug: 'git-init',
    command: 'git init',
    humanMeaning: '"Start tracking this folder with Git."',
    technicalMeaning: 'Creates a new, empty Git repository by adding a .git folder to the current directory.',
    whenToUse: "When you're starting a brand-new project and want Git to begin tracking it from scratch.",
    syntax: 'git init',
    example: 'git init',
    whatHappens: 'Git creates a .git folder here. Your existing files are untouched and untracked until you git add them.',
    mentalModel: 'Hand Git a blank notebook and say "start keeping a diary of this folder."',
    dangerLevel: 'safe',
    relatedCommands: ['git status', 'git clone'],
  },
  {
    slug: 'git-status',
    command: 'git status',
    humanMeaning: '"What is going on right now?"',
    technicalMeaning: 'Shows the state of the working directory and staging area compared to the last commit.',
    whenToUse: "Whenever you're not sure what's changed, what's staged, or what Git is about to do next. Safe to run constantly.",
    syntax: 'git status',
    example: 'git status',
    whatHappens: 'Git compares three things — your last commit, the staging area, and your working directory — and reports the differences. Nothing changes; it only reports.',
    mentalModel: 'Ask Git for a status report.',
    dangerLevel: 'safe',
    relatedCommands: ['git diff', 'git log'],
  },
  {
    slug: 'git-add',
    command: 'git add',
    humanMeaning: '"Choose these changes for my next snapshot."',
    technicalMeaning: 'Moves changes from the working directory into the staging area.',
    whenToUse: "When you've made changes you want included in your next commit.",
    syntax: 'git add <file>   (or git add . for everything in the current folder)',
    example: 'git add index.html',
    whatHappens: 'Git records the current version of the specified file(s) in the staging area. The working directory and the last commit are unaffected.',
    mentalModel: 'Put this change in the box that goes into the next checkpoint.',
    commonMistake: "Thinking git add saves or commits your work permanently. It only stages it — nothing is recorded in history until git commit runs.",
    dangerLevel: 'safe',
    relatedCommands: ['git status', 'git commit', 'git restore'],
    anatomy: [
      { token: 'git', explanation: 'The Git program.' },
      { token: 'add', explanation: 'Stage this change for the next commit.' },
      { token: 'index.html', explanation: 'The specific file to stage — or "." for everything changed.' },
    ],
  },
  {
    slug: 'git-commit',
    command: 'git commit',
    humanMeaning: '"I\'ve reached a meaningful point — remember it."',
    technicalMeaning: "Records a permanent snapshot of whatever is currently staged, along with a message describing it.",
    whenToUse: "After staging the changes you want to save as a checkpoint.",
    syntax: 'git commit -m "message"',
    example: 'git commit -m "Add login page"',
    whatHappens: 'Git takes everything in the staging area, saves it as a new commit object pointing back to the previous commit, and moves the current branch forward to it.',
    mentalModel: 'Press save on a checkpoint you can always come back to.',
    commonMistake: 'Committing without a clear message ("update", "fix"). Future-you (or a teammate) has to guess what actually changed.',
    dangerLevel: 'safe',
    relatedCommands: ['git add', 'git log', 'git status'],
    anatomy: [
      { token: 'git', explanation: 'The Git program.' },
      { token: 'commit', explanation: 'Create a commit / checkpoint.' },
      { token: '-m', explanation: 'Provide a commit message inline.' },
      { token: '"Add login page"', explanation: 'Describe what the checkpoint represents.' },
    ],
  },
  {
    slug: 'git-log',
    command: 'git log',
    humanMeaning: '"Show me everything that\'s happened so far."',
    technicalMeaning: "Lists the commit history reachable from the current branch, newest first.",
    whenToUse: 'When you want to see what commits exist, who made them, and when.',
    syntax: 'git log   (add --oneline for a compact view)',
    example: 'git log --oneline',
    whatHappens: 'Git walks backward through the chain of commits starting at HEAD, printing each one\'s hash, author, date, and message.',
    mentalModel: "Read your project's diary from most recent entry backward.",
    dangerLevel: 'safe',
    relatedCommands: ['git status', 'git diff'],
  },
  {
    slug: 'git-diff',
    command: 'git diff',
    humanMeaning: '"Show me exactly what changed, line by line."',
    technicalMeaning: 'Shows line-by-line differences between the working directory and the staging area (or the last commit, with --staged).',
    whenToUse: "When git status tells you a file changed and you want to see precisely what changed inside it.",
    syntax: 'git diff          (unstaged changes)\ngit diff --staged (staged changes)',
    example: 'git diff',
    whatHappens: "Git compares file contents and prints additions and removals inline, without changing anything.",
    mentalModel: 'Put two versions of a document side by side and highlight what\'s different.',
    dangerLevel: 'safe',
    relatedCommands: ['git status', 'git log'],
  },
  {
    slug: 'git-clone',
    command: 'git clone',
    humanMeaning: '"I don\'t have this project yet — give me a full copy."',
    technicalMeaning: "Downloads a complete copy of a remote repository, including its entire history, to a new folder on your machine.",
    whenToUse: "The first time you get a project that already exists on GitHub (or another remote).",
    syntax: 'git clone <url>',
    example: 'git clone https://github.com/example/project.git',
    whatHappens: "Git downloads every commit and branch from the remote, checks out the default branch into a new folder, and automatically names the remote 'origin.'",
    mentalModel: "Photocopy the entire book, cover to cover, not just today's page.",
    dangerLevel: 'safe',
    relatedCommands: ['git pull', 'git remote'],
  },
  {
    slug: 'git-remote',
    command: 'git remote add',
    humanMeaning: '"Connect this local repository to one on GitHub."',
    technicalMeaning: 'Registers a named reference to another repository so you can push to it and pull from it.',
    whenToUse: "After git init, when you've created an empty repository on GitHub and want to connect your local project to it.",
    syntax: 'git remote add origin <url>',
    example: 'git remote add origin https://github.com/example/project.git',
    whatHappens: "Git stores the URL under the name you gave it (conventionally 'origin') so future push/pull/fetch commands know where to go.",
    mentalModel: 'Save an address in your contacts so you can send mail to it by name.',
    dangerLevel: 'safe',
    relatedCommands: ['git push', 'git clone'],
  },
  {
    slug: 'git-push',
    command: 'git push',
    humanMeaning: '"Send my new commits to the remote."',
    technicalMeaning: "Uploads commits from your local branch to the corresponding branch on a remote repository.",
    whenToUse: "After committing locally, when you want your work backed up or visible to collaborators.",
    syntax: 'git push origin <branch>',
    example: 'git push origin main',
    whatHappens: "Git sends any commits the remote doesn't already have and moves the remote branch pointer forward to match yours.",
    mentalModel: 'Mail your new checkpoints to the shared mailbox.',
    commonMistake: "Confusing push with save. Push shares already-committed work — it doesn't create commits by itself.",
    dangerLevel: 'safe',
    relatedCommands: ['git pull', 'git fetch', 'git commit'],
  },
  {
    slug: 'git-pull',
    command: 'git pull',
    humanMeaning: '"I already have this project — bring me the latest changes."',
    technicalMeaning: "Downloads new commits from the remote and merges them into your current local branch.",
    whenToUse: "Before starting new work, or whenever you want your local branch to catch up with the remote.",
    syntax: 'git pull origin <branch>',
    example: 'git pull origin main',
    whatHappens: 'Git runs a fetch, then merges the retrieved remote branch into your current branch — which can produce a merge conflict if you and the remote both changed the same lines.',
    mentalModel: "Check the shared mailbox and merge whatever's new into your own copy.",
    dangerLevel: 'safe',
    relatedCommands: ['git fetch', 'git clone', 'git merge'],
  },
  {
    slug: 'git-fetch',
    command: 'git fetch',
    humanMeaning: '"Show me what\'s new on the remote, but don\'t change my files yet."',
    technicalMeaning: 'Downloads new commits and branches from the remote without merging them into your current branch.',
    whenToUse: "When you want to see what others have pushed before deciding whether to merge it in.",
    syntax: 'git fetch origin',
    example: 'git fetch origin',
    whatHappens: "Git updates your local record of the remote's branches (e.g. origin/main) but leaves your own branch and working directory untouched.",
    mentalModel: "Peek at what's in the shared mailbox without opening any of it yet.",
    commonMistake: "Expecting git fetch to update your working files. It only updates Git's knowledge of the remote — git pull or git merge is what actually brings changes in.",
    dangerLevel: 'safe',
    relatedCommands: ['git pull', 'git merge'],
  },
  {
    slug: 'git-branch',
    command: 'git branch',
    humanMeaning: '"List, create, or delete branches."',
    technicalMeaning: 'With no arguments, lists local branches. With a name, creates a new branch pointer at the current commit.',
    whenToUse: 'To see what branches exist, or to create a new one before switching to it.',
    syntax: 'git branch            (list)\ngit branch <name>     (create)',
    example: 'git branch feature/login',
    whatHappens: 'Git adds a new named pointer at your current commit. Nothing about your working directory changes until you switch to it.',
    mentalModel: 'Drop a new bookmark at the page you\'re currently on.',
    dangerLevel: 'safe',
    relatedCommands: ['git switch', 'git merge'],
  },
  {
    slug: 'git-switch',
    command: 'git switch',
    humanMeaning: '"Move me to a different branch."',
    technicalMeaning: 'Changes the currently checked-out branch, updating the working directory to match it.',
    whenToUse: 'When you want to start working on a different branch.',
    syntax: 'git switch <branch>       (switch)\ngit switch -c <branch>    (create and switch)',
    example: 'git switch feature/login',
    whatHappens: "Git moves HEAD to point at the target branch and updates your working directory files to match that branch's last commit.",
    mentalModel: 'Walk over to a different bookmark and pick up reading from there.',
    commonMistake: 'Switching branches with unsaved changes that conflict with the target branch — Git will refuse and ask you to commit or stash first, rather than silently discarding anything.',
    dangerLevel: 'safe',
    relatedCommands: ['git branch', 'git stash'],
  },
  {
    slug: 'git-merge',
    command: 'git merge',
    humanMeaning: '"Bring the changes from that branch into this one."',
    technicalMeaning: 'Combines the commit history of another branch into your current branch.',
    whenToUse: "When work on a separate branch is ready to become part of the branch you're on (often main).",
    syntax: 'git merge <branch>',
    example: 'git merge feature/login',
    whatHappens: "If the changes don't overlap, Git combines them automatically into a new merge commit. If they touch the same lines, Git pauses and asks you to resolve the conflict by hand.",
    mentalModel: 'Combine two separate drafts into one — automatically where possible, with your help where it isn\'t.',
    commonMistake: "Assuming a conflict means something is broken. It just means Git needs a human decision — nothing is lost, and git merge --abort backs out cleanly.",
    dangerLevel: 'safe',
    relatedCommands: ['git branch', 'git switch', 'git rebase'],
  },
  {
    slug: 'git-rebase',
    command: 'git rebase',
    humanMeaning: '"Replay my branch\'s commits on top of a different starting point."',
    technicalMeaning: "Moves or combines a sequence of commits onto a new base commit, rewriting their history.",
    whenToUse: "To keep a feature branch's history linear before merging, instead of creating a merge commit.",
    syntax: 'git rebase <branch>',
    example: 'git rebase main',
    whatHappens: "Git temporarily removes your branch's commits, updates the branch to the new base, then re-applies each commit one by one — which can produce conflicts that need resolving.",
    mentalModel: "Lift your stack of changes off the table and set it back down on a newer table.",
    commonMistake: "Rebasing commits that have already been pushed and that someone else might be building on — it rewrites history, which can cause serious confusion for anyone sharing that branch.",
    dangerLevel: 'caution',
    relatedCommands: ['git merge'],
  },
  {
    slug: 'git-restore',
    command: 'git restore',
    humanMeaning: '"Throw away my local changes to this file and go back to the last commit."',
    technicalMeaning: 'Restores a file in the working directory (or the staging area, with --staged) to a previous version.',
    whenToUse: "When you've made changes to a file you no longer want, and want to get back to the last committed version.",
    syntax: 'git restore <file>            (discard working directory changes)\ngit restore --staged <file>   (unstage, keep the edits)',
    example: 'git restore index.html',
    whatHappens: 'Without --staged, Git overwrites the file in your working directory with the version from the last commit — those edits are gone. With --staged, it only removes the file from the staging area; your edits stay in the working directory.',
    mentalModel: 'Rewind this one file back to its last checkpoint.',
    commonMistake: 'Running git restore <file> (without --staged) expecting it to just unstage — that variant discards the actual edits, not just the staging.',
    dangerLevel: 'caution',
    relatedCommands: ['git reset', 'git status', 'git stash'],
  },
  {
    slug: 'git-reset',
    command: 'git reset',
    humanMeaning: '"Move my current branch back to an earlier commit."',
    technicalMeaning: "Moves the current branch pointer to a specified commit, optionally also updating the staging area and working directory.",
    whenToUse: "To undo commits on a branch only you are working on — not one others have already pulled.",
    syntax: 'git reset <commit>          (default: keeps your changes, unstaged)\ngit reset --hard <commit>   (also discards working directory changes)',
    example: 'git reset HEAD~1',
    whatHappens: "By default (--mixed), Git moves the branch pointer and unstages everything since, but leaves your files on disk untouched — nothing is deleted. --hard additionally overwrites your working directory to match, discarding those changes for good.",
    mentalModel: 'Rewrite history to say a later checkpoint never happened — how much of your desk gets cleared along with it depends on the flag.',
    commonMistake: "Using git reset on commits you've already pushed and that a teammate has pulled. Prefer git revert for anything shared.",
    dangerLevel: 'caution',
    relatedCommands: ['git revert', 'git restore', 'git reflog'],
  },
  {
    slug: 'git-reset-hard',
    command: 'git reset --hard',
    humanMeaning: '"Go back to an earlier checkpoint and throw away everything since — no exceptions."',
    technicalMeaning: 'Moves the current branch to a specified commit and overwrites both the staging area and the working directory to match it exactly.',
    whenToUse: "Only when you're certain you want to permanently discard all uncommitted work and any commits after the target.",
    syntax: 'git reset --hard <commit>',
    example: 'git reset --hard HEAD~1',
    whatHappens: 'Git rewrites the branch pointer and immediately overwrites every tracked file in your working directory to match that commit. Uncommitted changes are gone; they are not recoverable through Git.',
    mentalModel: 'A hard reset doesn\'t just rewind the story — it also erases whatever you\'d scribbled in the margins.',
    commonMistake: 'Running this with uncommitted work you actually wanted to keep. There is no undo for the working-directory part of this command.',
    dangerLevel: 'high-caution',
    relatedCommands: ['git reset', 'git reflog', 'git stash'],
  },
  {
    slug: 'git-revert',
    command: 'git revert',
    humanMeaning: '"Undo the effect of a past commit, but keep it in the history."',
    technicalMeaning: 'Creates a brand-new commit that applies the exact opposite of a specified commit\'s changes.',
    whenToUse: 'To undo a commit that has already been pushed or shared with others.',
    syntax: 'git revert <commit>',
    example: 'git revert a1b2c3d',
    whatHappens: "Git figures out what that commit changed, applies the reverse, and records it as a new commit. The original commit stays in history — nothing is rewritten or hidden.",
    mentalModel: 'Add a new checkpoint that cancels out an old one, instead of pretending the old one never happened.',
    dangerLevel: 'caution',
    relatedCommands: ['git reset', 'git log'],
  },
  {
    slug: 'git-stash',
    command: 'git stash',
    humanMeaning: '"Set my unfinished changes aside for a moment."',
    technicalMeaning: 'Temporarily saves uncommitted changes (staged and unstaged) and reverts the working directory to match the last commit.',
    whenToUse: "When you need a clean working directory right now — to switch branches, pull, or handle something urgent — without committing half-finished work.",
    syntax: 'git stash          (save)\ngit stash pop      (bring the changes back)',
    example: 'git stash',
    whatHappens: 'Git records your current changes on a stack, then resets your working directory to the last commit. git stash pop re-applies the most recent stashed changes and removes them from the stack.',
    mentalModel: 'Shove your unfinished work in a drawer so your desk is clear — then pull it back out later.',
    commonMistake: 'Forgetting a stash exists. Stashed changes don\'t show up in git status once stashed — run git stash list to check.',
    dangerLevel: 'caution',
    relatedCommands: ['git switch', 'git restore'],
  },
  {
    slug: 'git-push-force',
    command: 'git push --force',
    humanMeaning: '"Overwrite the remote branch with my version, no matter what\'s there now."',
    technicalMeaning: "Pushes your branch to the remote even if it would overwrite commits on the remote that your local branch doesn't have.",
    whenToUse: "Rarely — mainly after rewriting your own local history (e.g. an interactive rebase) on a branch nobody else is using.",
    syntax: 'git push --force origin <branch>',
    example: 'git push --force origin feature/login',
    whatHappens: "Git replaces the remote branch's history with yours. Any commits that were on the remote but not in your local branch become unreachable from that branch — effectively lost for anyone who hasn't already fetched them.",
    mentalModel: 'Overwrite the shared mailbox\'s contents with your own copy, no matter what anyone else already put there.',
    commonMistake: "Force-pushing to a shared branch (like main) that others are actively working from — it can silently erase their pushed commits.",
    dangerLevel: 'high-caution',
    relatedCommands: ['git push', 'git rebase'],
  },
  {
    slug: 'git-reflog',
    command: 'git reflog',
    humanMeaning: '"Show me everywhere HEAD has pointed recently — even commits that got left behind."',
    technicalMeaning: "Lists a local log of every position HEAD has moved through, including commits that are no longer reachable from any branch.",
    whenToUse: "When you think you've lost a commit — after a hard reset, a bad rebase, or deleting a branch — and want to find it again.",
    syntax: 'git reflog',
    example: 'git reflog',
    whatHappens: "Git prints a list of recent HEAD positions with short hashes. You can git switch -c <new-branch> <hash> (or git reset) to bring any of them back.",
    mentalModel: "Git's own undo history — a record of where you've been, kept separately from the project history itself.",
    commonMistake: "Assuming a commit is gone forever after a reset or rebase. The reflog usually still has it, typically for around 90 days by default.",
    dangerLevel: 'safe',
    relatedCommands: ['git reset', 'git branch'],
  },
  {
    slug: 'git-clean',
    command: 'git clean',
    humanMeaning: '"Delete files Git isn\'t even tracking."',
    technicalMeaning: 'Permanently removes untracked files from the working directory.',
    whenToUse: "To clear out generated files, build artifacts, or scratch files that were never added to Git.",
    syntax: 'git clean -n   (preview — always run this first)\ngit clean -f   (actually delete)',
    example: 'git clean -n',
    whatHappens: 'Git deletes files that have never been staged or committed. Because they were never tracked, Git has no snapshot of them to recover — deletion is permanent.',
    mentalModel: 'Throw out anything on the desk that was never filed away — for good.',
    commonMistake: "Running git clean -f without git clean -n first. There's no undo, and it's easy to forget an important file was never git add-ed.",
    dangerLevel: 'high-caution',
    relatedCommands: ['git status', 'git reset --hard'],
  },
  {
    slug: 'git-cherry-pick',
    command: 'git cherry-pick',
    humanMeaning: '"Take that one commit from over there and apply it here."',
    technicalMeaning: 'Applies the changes introduced by a specific commit from another branch onto your current branch, as a new commit.',
    whenToUse: 'When you need just one specific fix or feature from another branch, without merging everything else on it.',
    syntax: 'git cherry-pick <commit>',
    example: 'git cherry-pick a1b2c3d',
    whatHappens: "Git takes the diff that commit introduced and replays it on top of your current branch, creating a new commit with a new hash — the original commit is untouched.",
    mentalModel: 'Photocopy one page out of another book and paste it into yours.',
    commonMistake: "Cherry-picking a commit that depends on earlier commits not yet in your branch — it can apply cleanly or produce a conflict depending on what actually changed.",
    dangerLevel: 'caution',
    relatedCommands: ['git merge', 'git rebase'],
  },
  {
    slug: 'git-rebase-interactive',
    command: 'git rebase -i',
    humanMeaning: '"Let me rewrite my last few commits before anyone sees them."',
    technicalMeaning: "Opens an editable list of recent commits, letting you reorder, reword, squash together, or drop them before they're replayed.",
    whenToUse: 'Cleaning up a messy local history — combining "fix typo" commits into the change they belong to — before pushing or opening a pull request.',
    syntax: 'git rebase -i HEAD~<n>',
    example: 'git rebase -i HEAD~3',
    whatHappens: "Git opens your editor with the last n commits listed oldest-first, each next to a command word (pick/reword/squash/drop) you can change, then replays them in the edited order — producing new commit hashes.",
    mentalModel: 'Editing your diary entries before publishing them — same story, cleaner telling.',
    commonMistake: "Interactively rebasing commits that have already been pushed and that someone else has pulled — same risk as a regular rebase, just easier to reach for by accident since it feels like routine cleanup.",
    dangerLevel: 'caution',
    relatedCommands: ['git rebase', 'git cherry-pick'],
  },
  {
    slug: 'git-tag',
    command: 'git tag',
    humanMeaning: '"Mark this exact commit as version 1.0."',
    technicalMeaning: 'Creates a named, permanent pointer to a specific commit — typically used to mark releases.',
    whenToUse: "When you've reached a point worth naming and coming back to later, like a release.",
    syntax: 'git tag <name>              (lightweight)\ngit tag -a <name> -m "msg"  (annotated)',
    example: 'git tag -a v1.0 -m "First release"',
    whatHappens: "Git records a reference pointing at your current commit. Unlike a branch, a tag doesn't move as you make new commits — it stays pinned to that one commit forever.",
    mentalModel: 'A bookmark that never moves, unlike a branch, which always follows your latest commit.',
    commonMistake: "Forgetting tags aren't pushed by default — git push doesn't send them; use git push --tags, or push the specific tag by name.",
    dangerLevel: 'safe',
    relatedCommands: ['git log'],
  },
  {
    slug: 'git-bisect',
    command: 'git bisect',
    humanMeaning: '"Help me find which commit broke this, by testing halfway points."',
    technicalMeaning: 'Performs a binary search through commit history, checking out successive commits for you to mark as good or bad, until it isolates the exact commit that introduced a problem.',
    whenToUse: "When something broke somewhere in the last N commits and you don't want to check them one by one.",
    syntax: 'git bisect start\ngit bisect bad\ngit bisect good <commit>',
    example: 'git bisect start',
    whatHappens: "Git checks out the commit halfway between your known-good and known-bad points; you test it and tell Git good or bad, and it narrows the range by half each round until one commit is left.",
    mentalModel: 'Guess-the-number, but the number is "which commit broke this" — Git tells you higher or lower each round.',
    commonMistake: "Forgetting to run git bisect reset when done — you're left checked out at a random historical commit (detached HEAD) until you do.",
    dangerLevel: 'safe',
    relatedCommands: ['git log', 'git switch'],
  },
  {
    slug: 'git-worktree',
    command: 'git worktree',
    humanMeaning: '"Let me check out a second branch in a separate folder, without touching this one."',
    technicalMeaning: 'Creates an additional working directory linked to the same repository, checked out to a different branch, so both can be worked on at once.',
    whenToUse: "When you need to work on two branches simultaneously — like testing a hotfix while a feature branch's build is still running — without stashing or switching back and forth.",
    syntax: 'git worktree add <path> <branch>',
    example: 'git worktree add ../hotfix main',
    whatHappens: "Git creates a new folder with its own checked-out files, sharing the same history and object database as the original — commits made in either are visible to both.",
    mentalModel: 'A second desk connected to the same filing cabinet — different surface, same underlying records.',
    commonMistake: "Trying to check out the same branch in two worktrees at once — Git blocks this, since one branch can only be checked out in one place at a time.",
    dangerLevel: 'safe',
    relatedCommands: ['git branch', 'git switch'],
  },
]
