// Relative, not `@/`: this file is also compiled by Vercel for the daily-push
// cron function, which cannot resolve the alias (see services/dailySelection.ts).
import type { DailyContentItem } from '../types.js'

/**
 * GitBit Daily's micro-learning feed (Section 6/7/8) — the same
 * knowledge base as Learn/Quick/Aha, reformatted for quick reads.
 * Feeds the future notification engine; `notificationEligible: false`
 * marks items too long for a push banner (kept for the in-app feed only).
 */
export const dailyContent: DailyContentItem[] = [
  {
    slug: 'vocab-head',
    type: 'vocabulary',
    title: 'HEAD',
    body: 'Think: "Where am I currently standing in Git history?"',
    relatedConcepts: ['head'],
    notificationEligible: true,
  },
  {
    slug: 'command-git-status',
    type: 'command',
    title: 'git status',
    body: 'git status is basically Git answering:\n"What\'s going on right now?"',
    relatedConcepts: ['staging-area'],
    notificationEligible: true,
  },
  {
    slug: 'mistake-add-does-not-save',
    type: 'common-mistake',
    title: "git add isn't a save button",
    body: 'git add does not permanently save your work.\nIt prepares changes for your next commit.',
    relatedConcepts: ['staging-area'],
    notificationEligible: true,
  },
  {
    slug: 'compare-clone-pull',
    type: 'comparison',
    title: 'clone vs. pull',
    body: 'git clone → "I need the project."\ngit pull → "I already have it. Give me the latest changes."',
    relatedConcepts: ['remote'],
    notificationEligible: true,
  },
  {
    slug: 'dyk-git-without-github',
    type: 'did-you-know',
    title: 'Did you know?',
    body: 'You can use Git without GitHub.',
    relatedConcepts: ['git-vs-github'],
    notificationEligible: true,
  },
  {
    slug: 'recall-staging-vs-commit',
    type: 'recall',
    title: 'Quick recall',
    body: "What's the difference between the staging area and a commit? (Hint: one of them is just a waiting room.)",
    relatedConcepts: ['staging-area', 'commit'],
    notificationEligible: true,
  },
  {
    slug: 'aha-commit-not-save',
    type: 'aha',
    title: 'Aha',
    body: "A commit is not a save button. It's a snapshot you chose to remember.",
    relatedConcepts: ['commit'],
    notificationEligible: true,
  },
  {
    slug: 'challenge-explain-status',
    type: 'mini-challenge',
    title: 'Mini challenge',
    body: 'Open any repo and run git status. Can you explain, in one sentence, everything it just told you?',
    relatedConcepts: ['staging-area'],
    notificationEligible: false,
  },
  {
    slug: 'vocab-staging-area',
    type: 'vocabulary',
    title: 'Staging Area',
    body: 'Think: "The waiting room for my next snapshot."',
    relatedConcepts: ['staging-area'],
    notificationEligible: true,
  },
  {
    slug: 'command-git-diff',
    type: 'command',
    title: 'git diff',
    body: 'git diff is Git answering:\n"Show me exactly what\'s different, line by line."',
    relatedConcepts: ['working-directory'],
    notificationEligible: true,
  },
  {
    slug: 'mistake-force-push-habit',
    type: 'common-mistake',
    title: 'Force-push, carefully',
    body: "git push --force can overwrite a teammate's commits without warning.\nReach for it only on branches nobody else is using.",
    relatedCommands: ['git push --force'],
    notificationEligible: true,
  },
  {
    slug: 'compare-reset-revert',
    type: 'comparison',
    title: 'reset vs. revert',
    body: 'git reset → rewrites history to say it never happened.\ngit revert → adds a new commit that cancels it out.',
    relatedConcepts: ['commit'],
    notificationEligible: true,
  },
  {
    slug: 'dyk-deleted-branch-keeps-commits',
    type: 'did-you-know',
    title: 'Did you know?',
    body: "Deleting a branch doesn't delete its commits right away — the bookmark's gone, not the history.",
    relatedConcepts: ['branch'],
    notificationEligible: true,
  },
  {
    slug: 'recall-detached-head',
    type: 'recall',
    title: 'Quick recall',
    body: 'Earlier you learned what HEAD points to. Can you explain detached HEAD without looking it up?',
    relatedConcepts: ['head', 'detached-head'],
    notificationEligible: true,
  },
  {
    slug: 'scenario-typo-in-commit-message',
    type: 'scenario',
    title: 'Real-world scenario',
    body: "You just noticed a typo in your last commit message, and you haven't pushed yet. No need to start over — git commit --amend lets you fix the message in place.",
    relatedConcepts: ['commit'],
    notificationEligible: false,
  },
  {
    slug: 'aha-branch-not-a-copy',
    type: 'aha',
    title: 'Aha',
    body: "A branch isn't a copy of your whole project. It's a bookmark that moves forward as you commit.",
    relatedConcepts: ['branch'],
    notificationEligible: true,
  },
  {
    slug: 'challenge-stage-and-unstage',
    type: 'mini-challenge',
    title: 'Mini challenge',
    body: 'Stage one file, then run git restore --staged on it. Watch what changes (and what doesn\'t) in git status between the two.',
    relatedConcepts: ['staging-area'],
    notificationEligible: false,
  },
  {
    slug: 'vocab-merge-conflict',
    type: 'vocabulary',
    title: 'Merge Conflict',
    body: 'Think: "Git found two answers to the same question and needs me to pick."',
    relatedConcepts: ['merge-conflict'],
    notificationEligible: true,
  },
  {
    slug: 'vocab-origin',
    type: 'vocabulary',
    title: 'origin',
    body: 'Think: "The nickname for the remote I cloned from."',
    relatedConcepts: ['origin', 'remote'],
    notificationEligible: true,
  },
  {
    slug: 'command-git-log-oneline',
    type: 'command',
    title: 'git log --oneline',
    body: 'git log --oneline is Git answering:\n"Give me the short version of what happened."',
    relatedConcepts: ['history'],
    relatedCommands: ['git log'],
    notificationEligible: true,
  },
  {
    slug: 'mistake-commit-everything',
    type: 'common-mistake',
    title: "Don't commit everything at once",
    body: 'git add . stages every change you made.\nCheck git status first, so a stray file doesn\'t sneak into your commit.',
    relatedConcepts: ['staging-area'],
    relatedCommands: ['git add', 'git status'],
    notificationEligible: true,
  },
  {
    slug: 'compare-fetch-pull',
    type: 'comparison',
    title: 'fetch vs. pull',
    body: 'git fetch → "Show me what changed on the remote."\ngit pull → "Show me, and merge it into my branch."',
    relatedConcepts: ['remote'],
    relatedCommands: ['git fetch', 'git pull'],
    notificationEligible: true,
  },
  {
    slug: 'dyk-dot-git-is-the-repo',
    type: 'did-you-know',
    title: 'Did you know?',
    body: 'Your whole Git history lives in one hidden folder: .git. Delete it and the files stay, but the history is gone.',
    relatedConcepts: ['dot-git-folder', 'repository'],
    notificationEligible: true,
  },
  {
    slug: 'recall-working-vs-staging',
    type: 'recall',
    title: 'Quick recall',
    body: 'You edited a file but haven\'t run git add. Is that change in the working directory, the staging area, or both?',
    relatedConcepts: ['working-directory', 'staging-area'],
    notificationEligible: true,
  },
  {
    slug: 'aha-remote-is-another-copy',
    type: 'aha',
    title: 'Aha',
    body: "GitHub isn't where Git lives. It's just another copy of your repository, one that other people can reach.",
    relatedConcepts: ['remote', 'git-vs-github'],
    notificationEligible: true,
  },
  {
    slug: 'vocab-untracked',
    type: 'vocabulary',
    title: 'Untracked file',
    body: 'Think: "A file Git can see but has never been told to care about."',
    relatedConcepts: ['tracked-vs-untracked'],
    notificationEligible: true,
  },
  {
    slug: 'command-git-stash',
    type: 'command',
    title: 'git stash',
    body: 'git stash is Git saying:\n"I\'ll hold these changes for you. Come back for them later."',
    relatedConcepts: ['stash', 'uncommitted-changes'],
    relatedCommands: ['git stash'],
    notificationEligible: true,
  },
  {
    slug: 'mistake-reset-hard-uncommitted',
    type: 'common-mistake',
    title: 'reset --hard has no undo for this',
    body: 'git reset --hard throws away uncommitted changes for good.\nCommitted work can come back via reflog. Uncommitted work can\'t.',
    relatedConcepts: ['uncommitted-changes'],
    relatedCommands: ['git reset --hard', 'git reflog'],
    notificationEligible: true,
  },
  {
    slug: 'compare-switch-restore',
    type: 'comparison',
    title: 'switch vs. restore',
    body: 'git switch → "Take me to another branch."\ngit restore → "Put this file back the way it was."',
    relatedConcepts: ['branch', 'working-directory'],
    relatedCommands: ['git switch', 'git restore'],
    notificationEligible: true,
  },
  {
    slug: 'dyk-reflog-safety-net',
    type: 'did-you-know',
    title: 'Did you know?',
    body: 'git reflog remembers everywhere HEAD has been, even commits you "lost" to a reset.',
    relatedConcepts: ['head'],
    relatedCommands: ['git reflog'],
    notificationEligible: true,
  },
  {
    slug: 'recall-what-is-a-commit',
    type: 'recall',
    title: 'Quick recall',
    body: 'A commit stores a snapshot, a message, an author, and one more thing that links it into history. What is it?',
    relatedConcepts: ['commit', 'history'],
    notificationEligible: true,
  },
  {
    slug: 'aha-merge-joins-histories',
    type: 'aha',
    title: 'Aha',
    body: "A merge doesn't copy files between branches. It creates one commit with two parents, joining two histories.",
    relatedConcepts: ['branch', 'history'],
    relatedCommands: ['git merge'],
    notificationEligible: true,
  },
  {
    slug: 'scenario-committed-to-wrong-branch',
    type: 'scenario',
    title: 'Real-world scenario',
    body: "You committed to main but meant to use a feature branch, and you haven't pushed. Create the branch where you are with git branch feature, then move main back with git reset --hard HEAD~1. The commit now lives only on feature.",
    relatedConcepts: ['branch', 'rewriting-history'],
    relatedCommands: ['git branch', 'git reset --hard'],
    notificationEligible: false,
  },
  {
    slug: 'challenge-read-the-graph',
    type: 'mini-challenge',
    title: 'Mini challenge',
    body: 'Run git log --oneline --graph --all in any repo with branches. Find where two lines split, and where (if anywhere) they join again.',
    relatedConcepts: ['history', 'branch'],
    relatedCommands: ['git log'],
    notificationEligible: false,
  },
  {
    slug: 'vocab-pull-request',
    type: 'vocabulary',
    title: 'Pull Request',
    body: 'Think: "Please review my branch before it joins main."',
    relatedConcepts: ['pull-request'],
    notificationEligible: true,
  },
  {
    slug: 'mistake-rewrite-shared-history',
    type: 'common-mistake',
    title: "Don't rewrite shared history",
    body: 'Rebasing or amending commits you already pushed changes their IDs.\nAnyone who pulled the old ones now has a mess to untangle.',
    relatedConcepts: ['rewriting-history'],
    relatedCommands: ['git rebase', 'git push --force'],
    notificationEligible: true,
  },
  {
    slug: 'compare-merge-rebase',
    type: 'comparison',
    title: 'merge vs. rebase',
    body: 'git merge → "Join the two histories with a merge commit."\ngit rebase → "Replay my commits on top, as if I started later."',
    relatedConcepts: ['history'],
    relatedCommands: ['git merge', 'git rebase'],
    notificationEligible: true,
  },
  {
    slug: 'dyk-commit-ids-are-fingerprints',
    type: 'did-you-know',
    title: 'Did you know?',
    body: "A commit's ID is a fingerprint of its content and its parent. Change anything, even the message, and you get a new ID.",
    relatedConcepts: ['commit'],
    notificationEligible: true,
  },
]
