import { lazy } from 'react'

export const HomePage = lazy(() => import('@/features/home/HomePage'))
export const QuickPage = lazy(() => import('@/features/quick/QuickPage'))
export const CommandDetailPage = lazy(() => import('@/features/quick/CommandDetailPage'))
export const LearnPage = lazy(() => import('@/features/learn/LearnPage'))
export const LevelPage = lazy(() => import('@/features/learn/LevelPage'))
export const ConceptPage = lazy(() => import('@/features/learn/ConceptPage'))
export const AhaPage = lazy(() => import('@/features/aha/AhaPage'))
export const AhaDetailPage = lazy(() => import('@/features/aha/AhaDetailPage'))
export const QuizPage = lazy(() => import('@/features/quiz/QuizPage'))
export const QuizQuestionPage = lazy(() => import('@/features/quiz/QuizQuestionPage'))
export const SosPage = lazy(() => import('@/features/sos/SosPage'))
export const SosDetailPage = lazy(() => import('@/features/sos/SosDetailPage'))
export const TerminalPage = lazy(() => import('@/features/terminal/TerminalPage'))
export const DailyPage = lazy(() => import('@/features/daily/DailyPage'))
export const SearchPage = lazy(() => import('@/features/search/SearchPage'))
export const DesignSystemPage = lazy(() => import('@/features/design-system/DesignSystemPage'))
export const NotFoundPage = lazy(() => import('@/features/not-found/NotFoundPage'))
