import type { GitConcept } from '@/content/types'

/**
 * Level 0-3 core vocabulary, plus the handful of Level 5/6 terms GitBit
 * SOS and Aha depend on (head, detached-head, merge-conflict). Phase 4
 * prioritizes foundations over exhaustive coverage (Section 38).
 */
export const concepts: GitConcept[] = [
  {
    slug: 'git',
    term: 'Git',
    category: 'core-concept',
    plainEnglish: 'A tool that remembers every version of your project so you never have to.',
    mentalModel: 'A very thorough diary for your code — it can tell you exactly what changed, when, and why.',
    technicalExplanation:
      'Git is a distributed version control system. It tracks changes to a set of files over time as a series of snapshots (commits), lets you branch off to work on something without disturbing the main line of work, and lets multiple people combine their changes back together.',
    whenToUse: 'Any time you want a project to have a real, searchable history instead of a folder full of "final_v3_FINAL" files.',
    difficulty: 'beginner',
    relatedConcepts: ['repository', 'commit', 'history'],
    ahaPotential: true,
  },
  {
    slug: 'repository',
    term: 'Repository',
    category: 'core-concept',
    plainEnglish: "A project that Git is keeping track of. People usually just call it a 'repo.'",
    mentalModel: 'A folder, plus its entire memory of every change ever made inside it.',
    technicalExplanation:
      "A repository is a project directory that contains a .git folder. That .git folder holds the full history of commits, branches, and configuration — everything Git needs to reconstruct any past version of the project.",
    whenToUse: "When you hear 'repo,' it just means 'this specific Git-tracked project.'",
    difficulty: 'beginner',
    relatedConcepts: ['git', 'dot-git-folder', 'working-directory'],
  },
  {
    slug: 'working-directory',
    term: 'Working Directory',
    category: 'core-concept',
    plainEnglish: 'The actual files on your computer, exactly as you see them in your editor right now.',
    mentalModel: 'Your desk — whatever you\'re currently working on sits here, staged or not, committed or not.',
    technicalExplanation:
      "The working directory is the set of files you can see and edit on disk. It reflects whatever commit you currently have checked out, plus any changes you've made since. Git compares this against the staging area and the last commit to figure out what's changed.",
    difficulty: 'beginner',
    relatedConcepts: ['working-tree', 'staging-area', 'repository'],
  },
  {
    slug: 'working-tree',
    term: 'Working Tree',
    category: 'core-concept',
    plainEnglish: "Git's own name for the same thing as your working directory.",
    mentalModel: "Don't overthink this one — it's the same desk, just Git's official term for it.",
    technicalExplanation:
      "Git's documentation and command output (git status, error messages) use 'working tree' as the formal name for what most people casually call the 'working directory' — the checked-out files on disk. They refer to the same thing; GitBit uses whichever term fits the sentence better.",
    difficulty: 'beginner',
    relatedConcepts: ['working-directory'],
    commonMistake: "Thinking 'working tree' and 'working directory' are two different parts of Git. They're not — same thing, two names.",
  },
  {
    slug: 'dot-git-folder',
    term: '.git',
    category: 'core-concept',
    plainEnglish: 'The hidden folder where Git actually keeps everything.',
    mentalModel: "Your project's memory, stored right next to the project itself.",
    technicalExplanation:
      'The .git folder holds the full commit history, all branches, tags, configuration, and Git\'s internal object database. Deleting it turns a Git repository back into an ordinary folder — all history is gone, but your current files are untouched.',
    whenToUse: "You'll rarely open it directly, but knowing it exists explains where Git \"keeps\" everything.",
    difficulty: 'beginner',
    relatedConcepts: ['repository'],
    dangerLevel: 'high-caution',
    commonMistake: 'Deleting the .git folder to "start fresh" — this permanently destroys the entire project history, not just the current state.',
  },
  {
    slug: 'commit',
    term: 'Commit',
    category: 'core-concept',
    plainEnglish: 'A checkpoint in your project that Git will remember forever.',
    mentalModel: 'A save point in a video game — you can always come back to exactly this moment.',
    technicalExplanation:
      "A commit is a recorded snapshot of your entire project at a point in time, plus metadata (author, timestamp, message, and a pointer to the previous commit). Git stores this efficiently — files that haven't changed since the last commit aren't duplicated on disk.",
    example: 'git commit -m "Add login page"',
    whenToUse: "When you've reached a meaningful point in your work and want Git to remember it.",
    difficulty: 'beginner',
    relatedCommands: ['git commit', 'git log'],
    relatedConcepts: ['staging-area', 'history'],
    ahaPotential: true,
    notificationEligible: true,
  },
  {
    slug: 'history',
    term: 'History',
    category: 'core-concept',
    plainEnglish: 'The full timeline of every commit ever made to a project.',
    mentalModel: "A project's story, told one checkpoint at a time.",
    technicalExplanation:
      'History is the chain of commits, each pointing back to its parent(s), that you can walk with git log. Because each commit is linked to the one before it, Git can reconstruct the exact state of the project at any past point.',
    example: 'git log',
    difficulty: 'beginner',
    relatedCommands: ['git log'],
    relatedConcepts: ['commit'],
  },
  {
    slug: 'staging-area',
    term: 'Staging Area',
    category: 'core-concept',
    plainEnglish: "The changes you've chosen for your next snapshot.",
    mentalModel: 'A waiting room for your next commit — nothing enters history until it steps in here first.',
    technicalExplanation:
      "The staging area (also called the index) is a file Git uses to build the next commit. git add moves changes from the working directory into the staging area; git commit takes a snapshot of whatever is staged. Staging a file doesn't create a commit — it just prepares it for the next one.",
    example: 'git add index.html',
    whenToUse: "When you want to choose exactly which changes go into your next commit, instead of committing everything at once.",
    whatHappens: 'Git records the current version of the file in the index, separate from both the working directory and the last commit.',
    commonMistake: "Thinking git add saves or commits your work. It only stages it — nothing is permanently recorded until git commit runs.",
    difficulty: 'beginner',
    relatedCommands: ['git add', 'git commit', 'git status', 'git restore'],
    relatedConcepts: ['working-directory', 'commit'],
    ahaPotential: true,
    notificationEligible: true,
  },
  {
    slug: 'git-vs-github',
    term: 'Git vs. GitHub',
    category: 'core-concept',
    plainEnglish: 'Git is the tool. GitHub is one place you can put your Git projects online.',
    mentalModel: 'Git is like email — an open protocol anyone can run. GitHub is like Gmail — one popular service built on top of it.',
    technicalExplanation:
      'Git is a version control system that runs entirely on your own machine and needs no internet connection or third party. GitHub is a web platform that hosts Git repositories and adds collaboration features (pull requests, issues, code review) on top of plain Git. GitLab, Bitbucket, and self-hosted servers are other services that do the same job as GitHub.',
    whenToUse: 'Whenever you\'re unsure whether something is "Git" or "GitHub" — if it\'s about history, commits, or branches, it\'s Git; if it\'s about pull requests, stars, or issues, it\'s GitHub.',
    commonMistake: 'Assuming you need GitHub (or any internet connection) to use Git. You can init, commit, branch, and view history entirely offline.',
    difficulty: 'beginner',
    relatedConcepts: ['repository', 'remote'],
    ahaPotential: true,
    notificationEligible: true,
  },
  {
    slug: 'remote',
    term: 'Remote',
    category: 'collaboration',
    plainEnglish: "A copy of the repository that lives somewhere else — usually on GitHub.",
    mentalModel: 'A shared mailbox your team all sends updates to and picks updates up from.',
    technicalExplanation:
      "A remote is a named reference to another copy of the repository, typically hosted on a server like GitHub. Your local repository can have one or more remotes. git push sends your commits to a remote; git fetch/git pull bring its commits to you.",
    whenToUse: 'When you want to back up your work online or collaborate with other people.',
    difficulty: 'beginner',
    relatedCommands: ['git remote', 'git push', 'git pull', 'git fetch', 'git clone'],
    relatedConcepts: ['origin', 'git-vs-github'],
  },
  {
    slug: 'origin',
    term: 'Origin',
    category: 'collaboration',
    plainEnglish: "The default nickname Git gives the remote you cloned from.",
    mentalModel: "Just a label — like naming your home Wi-Fi 'Home' instead of typing the router's address every time.",
    technicalExplanation:
      "'origin' is a convention, not a special keyword — it's simply the name Git automatically assigns to the remote a repository was cloned from. You can rename it or add other remotes with different names.",
    example: 'git push origin main',
    commonMistake: "Thinking 'origin' is a required or magic name. It's just the default — any name would work.",
    difficulty: 'beginner',
    relatedConcepts: ['remote'],
  },
  {
    slug: 'branch',
    term: 'Branch',
    category: 'workflow',
    plainEnglish: 'An independent line of work you can experiment on without touching the main project.',
    mentalModel: "Not a full copy of your project — more like a bookmark that moves forward as you commit.",
    technicalExplanation:
      "A branch is simply a movable pointer to a commit. Creating a branch doesn't duplicate any files; it just adds a new named pointer at your current commit. As you commit on that branch, the pointer moves forward, while other branches keep pointing wherever they were.",
    whenToUse: 'When you want to try something — a feature, a fix, an experiment — without affecting the main line of work until it\'s ready.',
    commonMistake: "Imagining a branch copies your entire project into a separate folder. It doesn't — branching is nearly instant precisely because it's just a pointer, not a copy.",
    difficulty: 'beginner',
    relatedCommands: ['git branch', 'git switch', 'git merge'],
    relatedConcepts: ['head', 'merge-conflict'],
    ahaPotential: true,
    notificationEligible: true,
  },
  {
    slug: 'head',
    term: 'HEAD',
    category: 'workflow',
    plainEnglish: 'Wherever you currently are in your project\'s history.',
    mentalModel: '"You are here" on a map — HEAD marks your current position, not a fixed place.',
    technicalExplanation:
      "HEAD is a pointer that usually points to the branch you have checked out, which in turn points to a commit. Moving HEAD (by switching branches or checking out a specific commit) changes which snapshot your working directory reflects.",
    difficulty: 'intermediate',
    relatedConcepts: ['detached-head', 'branch'],
    ahaPotential: true,
  },
  {
    slug: 'detached-head',
    term: 'Detached HEAD',
    category: 'advanced',
    plainEnglish: "You've checked out a specific commit instead of a branch — you're looking at old history, not standing on a path.",
    mentalModel: "You've stepped off the trail to look at an old landmark. You can look around freely, but if you walk further without marking your spot, it can be hard to find your way back.",
    technicalExplanation:
      "Normally HEAD points to a branch, which points to a commit. In detached HEAD state, HEAD points directly to a commit instead. Any new commits you make here aren't on any branch — if you switch away without creating a branch first, they can become hard to find (though they aren't deleted right away).",
    whenToUse: "Useful for briefly inspecting old history (git checkout <commit>). Before making new commits from here, create a branch so they don't get orphaned.",
    commonMistake: 'Making real work in detached HEAD and then switching branches without saving it first — the commits still exist, but nothing points to them anymore, so they stop showing up in git log.',
    difficulty: 'advanced',
    dangerLevel: 'caution',
    relatedConcepts: ['head', 'branch'],
    relatedCommands: ['git switch', 'git branch'],
  },
  {
    slug: 'merge-conflict',
    term: 'Merge Conflict',
    category: 'collaboration',
    plainEnglish: 'Git found two changes to the exact same lines and needs you to pick which one wins.',
    mentalModel: 'Two people editing the same sentence in a shared document at the same time — someone has to decide the final wording.',
    technicalExplanation:
      "A merge conflict happens when Git tries to combine two branches that both changed the same lines of the same file (or one edited a file the other deleted) and can't automatically decide how to combine them. Git marks the conflicting sections in the file for you to resolve by hand, then you stage the resolved file and commit.",
    whenToUse: "You don't choose this — Git tells you when it happens, usually during git merge or git pull.",
    commonMistake: "Panicking. A merge conflict doesn't mean anything is broken or lost — it just means Git needs a human decision before it can continue.",
    difficulty: 'intermediate',
    dangerLevel: 'caution',
    relatedCommands: ['git merge', 'git status', 'git diff'],
    relatedConcepts: ['branch'],
  },
  {
    slug: 'pull-request',
    term: 'Pull Request',
    category: 'collaboration',
    plainEnglish: "A request to merge your branch into someone else's, with a place to discuss and review the changes first.",
    mentalModel: 'Raising your hand before merging — "here\'s what I changed, can someone take a look?"',
    technicalExplanation:
      "A pull request (PR) is a feature GitHub, GitLab, and similar hosts add on top of Git — it is not a Git command, and Git itself has no built-in concept of one. A PR is a structured request, built on a pushed branch, that lets collaborators review the diff, leave comments, run automated checks, and approve before the branch is merged into another (usually main). Merging a PR just runs an ordinary merge on the host's servers.",
    whenToUse: "When your work is ready for feedback, or ready to become part of the main project, and other people need visibility before it does.",
    whatHappens: "Nothing changes in Git's own history when a PR opens — it only points at two branches on the remote and tracks their diff. History only changes once the PR is actually merged.",
    commonMistake: "Assuming 'pull request' is a Git command you can run. It isn't — it's a workflow layer hosting services add on top of push, branch, and merge.",
    difficulty: 'intermediate',
    relatedCommands: ['git push', 'git merge'],
    relatedConcepts: ['branch', 'merge-conflict', 'git-vs-github'],
    ahaPotential: true,
  },
]
